sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8

before_install:
  - sudo apt-get -y install python3-pip
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U coala-bears

script: mvn clean verify
